- name: Add MongoDB apt key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    state: present

- name: Add MongoDB repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse
    state: present
    filename: mongodb
  register: mongo_repo

- name: Reload apt cache
  apt:
    update_cache: yes
  when: mongo_repo.changed

- name: Install MongoDB package
  apt:
    name: mongodb-org
    state: present

- name: Configure mongod
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
  notify: Restart mongod

- name: Ensure that mongod is started and enabled
  service:
    name: mongod
    state: started
    enabled: yes

- name: Restart mongod if needed
  meta: flush_handlers